spring.datasource.url=jdbc:sqlite:financas.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.auto-commit=false

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.show-sql=true

# Ignore warnings on SQLite without explicit transactions
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
